# DigitalOcean App Platform Specification
# Deploy directly from GitHub

name: astrosurveillance
region: nyc
services:
  - name: edge-server
    # Build from Dockerfile
    dockerfile_path: Dockerfile
    
    # Or use GitHub repository
    github:
      repo: astrobsm/astrosurveillance
      branch: main
      deploy_on_push: true
    
    # Instance size (basic-xxs = $5/month, basic-xs = $10/month)
    instance_size_slug: basic-xxs
    instance_count: 1
    
    # HTTP port
    http_port: 3080
    
    # Health check
    health_check:
      http_path: /api/system/health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3080"
      - key: HOST
        value: "0.0.0.0"
      - key: ALARM_DURATION
        value: "10"
      - key: RECORDING_DURATION
        value: "60"
    
    # Routes
    routes:
      - path: /

# Optional: Add a static site for web preview
static_sites:
  - name: web-dashboard
    github:
      repo: astrobsm/astrosurveillance
      branch: main
      deploy_on_push: true
    source_dir: web-preview
    routes:
      - path: /dashboard
